"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let name = "Naresh ";
const age = 47;
const isValidUser = false;
const billAmount = 100.55;
//age = 48;
console.log("Name:" + name.length);
console.log("Age:" + age);
console.log("isValidUser:" + isValidUser);
console.log("Bill Amount:" + billAmount);
