"use strict";
exports.__esModule = true;
var name = "Naresh ";
var age = 47;
var isValidUser = false;
var billAmount = 100.55;
//age = 48;
console.log("Name:" + name.length);
console.log("Age:" + age);
console.log("isValidUser:" + isValidUser);
console.log("Bill Amount:" + billAmount);
